# -*- coding: utf-8 -*-
siteyear = {
    'Cedar2010':{'region': 'Delmarva', 'site': 'Cedar',
                    'year': '2010', 'code': 'cei10',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Cedar2012':{'region': 'Delmarva', 'site': 'Cedar',
                    'year': '2012', 'code': 'cei12',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Cedar2014':{'region': 'Delmarva', 'site': 'Cedar',
                    'year': '2014', 'code': 'cei14',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Smith2010':{'region': 'Delmarva', 'site': 'Smith',
                    'year': '2010', 'code': 'smi10',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Smith2012':{'region': 'Delmarva', 'site': 'Smith',
                    'year': '2012', 'code': 'smi12',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Smith2014':{'region': 'Delmarva', 'site': 'Smith',
                    'year': '2014', 'code': 'smi14',
                    'MHW':0.34, 'MLW':-0.56, 'MTL':None},
    'Assateague2014':{'region': 'Delmarva', 'site': 'Assateague',
                    'year': '2014', 'code': 'asis14',
                    'MHW':0.34, 'MLW':-0.13, 'MTL':None},
    'ParkerRiver2014':{'region': 'Massachusetts', 'site': 'ParkerRiver',
                    'year': '2014', 'code': 'pr14',
                    'MHW':1.22, 'MLW':-1.37, 'MTL':None},
    'Forsythe2014':{'region': 'NewJersey', 'site': 'Forsythe',
                    'year': '2014', 'code': 'ebf14',
                    'MHW':0.43, 'MLW':-0.61, 'MTL':None},
    }
